language: python

python:
    - 3.7

env:
    - CTAPIPE_VERSION="v0.7.0" CTAPIPE_IO_LST_VERSION="v0.4.1" PROTOZFITS_VERSION=v1.4.2 LSTCHAIN_VERSION="v0.4.3" PROTOPIPE_VERSION="v0.2.1"
    - CTAPIPE_VERSION="master" CTAPIPE_IO_LST_VERSION="master" PROTOZFITS_VERSION="master" LSTCHAIN_VERSION="master" PROTOPIPE_VERSION="master"

matrix:
  allow_failures:
      - name: "yes, masters"
        env: CTAPIPE_VERSION="master" CTAPIPE_IO_LST_VERSION="master" PROTOZFITS_VERSION="master" PROTOPIPE_VERSION="master" LSTCHAIN_VERSION="master"

  include:
      - name: "latest releases"
        env: CTAPIPE_VERSION="v0.7.0" CTAPIPE_IO_LST_VERSION="v0.2" PROTOZFITS_VERSION=v1.4.2 LSTCHAIN_VERSION="v0.4.3" PROTOPIPE_VERSION="v0.2.1"
      - name: "proto master"
        env: CTAPIPE_VERSION="master" PROTOPIPE_VERSION="master"

before_install:

    # Use utf8 encoding. Should be default, but this is insurance
    # against future changes
    - export PYTHONIOENCODING=UTF8
    - export MPLBACKEND=Agg

    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    - conda info -a # Useful for debugging any issues with conda

install:
    - conda env create -n testbuild --file environment.yml
    - conda activate testbuild
    - pip install https://github.com/cta-observatory/ctapipe/archive/$CTAPIPE_VERSION.tar.gz
    - pip install https://github.com/cta-observatory/ctapipe_io_lst/archive/$CTAPIPE_IO_LST_VERSION.tar.gz
    - pip install https://github.com/cta-sst-1m/protozfitsreader/archive/$PROTOZFITS_VERSION.tar.gz
    - pip install https://github.com/cta-observatory/protopipe/archive/$PROTOPIPE_VERSION.tar.gz
    - '[[ "$LSTCHAIN_VERSION" = "" ]] || pip install https://github.com/cta-observatory/cta-lstchain/archive/$LSTCHAIN_VERSION.tar.gz'



script:
    - pytest test
