language: python

python:
  - 3.7

env:
  - $CTAPIPE_VERSION="master"

before_install:
    # Use utf8 encoding. Should be default, but this is insurance
    # against future changes
    - export PYTHONIOENCODING=UTF8
    - export MPLBACKEND=Agg
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh

install:
    - conda env create -n testbuild --file environment.yml
    - conda activate testbuild
    - pip install https://github.com/cta-observatory/ctapipe/archive/$CTAPIPE_VERSION.tar.gz

script:
    - pytest test
